version: '2'
services:
  postgresql_spa:
    image: 'docker.io/bitnami/postgresql:latest'
    environment:
      - POSTGRESQL_USERNAME=postgres
      - POSTGRESQL_PASSWORD=Ole2020...
      - POSTGRESQL_DATABASE=spa_dev
      - POSTGRESQL_SYNCHRONOUS_COMMIT_MODE=on
    volumes:
      - './db_volume:/bitnami'
  phppgadmin_spa:
    image: 'docker.io/bitnami/phppgadmin:latest'
    ports:
      - '8081:8080'
      - '5432:8443'
    depends_on:
      - postgresql_spa
